### ISSUE TITLE
Eclipse Marketplace failed with an error In Installed tab when build up to version 4.32.0

### ISSUE THREAD

**Issue by LonieN** [eclipse-platform/www.eclipse.org-eclipse#190]
An anyone help me with this error when I update to Eclipse version 4.32.0. Thank you

org.eclipse.core.runtime.CoreException: Unexpected response for
'2306961,1103239,3581018,1617241,4716941,5012014,
4528322,1166,4290168,5026683,5321178,2177882,2433251,264,3184658'

![image](https://github.com/eclipse-platform/www.eclipse.org-eclipse/assets/30336860/4a85d423-3aa7-4e5d-98b0-532365377688)

![image](https://github.com/eclipse-platform/www.eclipse.org-eclipse/assets/30336860/a65e27f5-6738-4db7-9018-ec0f16322411)

![image](https://github.com/eclipse-platform/www.eclipse.org-eclipse/assets/30336860/44c899c8-4ffb-4ffc-a511-7ba4d9046ecb)

**Comment by merks** [comment]
Please report the problem here:

https://github.com/eclipse-mpc/epp.mpc/issues

I cannot move the issue to a different GitHub organization.

That looks like a very old version of Mylyn given that 4.3.0 was the most recent release:

https://download.eclipse.org/mylyn/updates/

Better to install from this site:

https://download.eclipse.org/mylyn/updates/release/latest

There has been some feature renaming that might cause update problems.  You might need to uninstall all the old versions before installing new ones.
